### ISSUE TITLE
Not updating pull request status

### ISSUE THREAD

**Issue by suneet64** [magestats/issues#1]
Hi Guys,

One of my pull request (https://github.com/magento/magento2/pull/19532) merged 4 days ago but in MageStats, it is still showing open.

Can you please check this?

https://magestats.net/contributor/suneet64

![screenshot-magestats net-2019 01 23-22-31-52](https://user-images.githubusercontent.com/34968044/51623572-05225100-1f5f-11e9-89f6-e7edd7c9c796.png)

**Comment by suneet64** [comment]
@mhauri, it would be great if you can check this. Thank you!

**Comment by mhauri** [comment]
Thank you @suneet64 for reporting the issue. It's fixed now.

**Comment by suneet64** [comment]
Hi @mhauri, it seems that there is still an issue. Please refer to the attached screenshots.

![contributorsin2018](https://user-images.githubusercontent.com/34968044/51818807-38b20200-22f6-11e9-81e4-17becb8bde0a.png)
![suneet64](https://user-images.githubusercontent.com/34968044/51818816-410a3d00-22f6-11e9-9cd9-ab95f7b700f1.png)
